/*
The Fibonacci sequence is the series of numbers 0, 1, 1, 2, 3, 5, 8,....
Formally, it can be expressed as:
fib0 =0
fib1 =1
fibn = fibn−1 + fibn−2
Write a multithreaded program that generates the Fibonacci sequence.
This program should work as follows: On the command line, the user will enter the number of Fibonacci numbers that the program is to generate.
The program will then create a separate thread that will generate the Fibonacci numbers, placing the sequence in data that can be shared by the threads (an array is probably the most convenient data structure).
When the thread finishes execution, the parent thread will output the sequence generated by the child thread.
Because the parent thread cannot begin outputting the Fibonacci sequence until the child thread finishes, the parent thread will have to wait for the child thread to finish.
Use the techniques described in Section 4.4 to meet this requirement.

@authors A01027541, A00826156, A01364718, A01335324
Operating System ITESM CSF
*/

#include "pthread.h"
#include <stdio.h>
#include <stdlib.h>

int sum; /* this data is shared by the thread(s) */
void *runner(void *param); /* this is the thread */

int main(int argc, char *argv[])
{
	int count, i; /* counters */

  /* Verify two args were passed in */
	if (argc != 2) {
		fprintf(stderr,"usage: pthreads <integer value>\n");
		exit(1);
	}

  /* set of thread sttributes */
	pthread_attr_t attr; 
  
  /* Count = size */
	count = atoi(argv[1]);
  
  /* Array sized to the input of fibonacci numbers to calculate */
  int fibos[count-1]; 

  /* Verify the input is greater than 1 */
	if (count < 1) {
		fprintf(stderr,"%d must be>= 1\n", count);
		exit(1);
	}

  /* Get the default attributes */
	pthread_attr_init(&attr);

  printf("Fib list es: \n");
	for(i=1;i<=count;i++)
  {
    /* the thread identifier */
		pthread_t thread; 
    /* Create the thread */
		pthread_create(&thread,&attr,runner,(void*)i);
    /* Wait for the thread to exit */
		pthread_join(thread,NULL);	
    fibos[i-1] = sum; /* Fibonacci number into array */
	}	

  for(i=0; i<count; i++) /* Prints array */
  {
    printf("%d ",fibos[i]);  
  }
}

/* The thread will begin control in this function */
void *runner(void *param)
{
	sum = fibonacci((int)param); /* Get Fibonacci number */

  /* Exit the thread */
	pthread_exit(0);
}

int fibonacci (int x) /* Fibonacci function */
{
    if (x <= 1) {
        return 1;
    }
    return fibonacci(x-1) + fibonacci(x-2);
}